name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Step 1: Creating the 'resume' directory in /var/www/html."
            sudo mkdir -p /var/www/html/resume
            
            echo "Step 2: Copying files to the 'resume' directory."
            # Copy files from your project's directory to /var/www/html/resume
            sudo cp -r /home/ubuntu/your_project_directory/* /var/www/html/resume/
            echo "Step 3: Files copied to /var/www/html/resume."
