name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your main branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH key for accessing the EC2 server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Add your private key as a secret

      # Step 3: Rsync the project files to the server
      - name: Deploy project via rsync
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}  # The SSH private key for connecting to EC2
          REMOTE_HOST: ${{ secrets.HOST_DNS }}          # The IP address or DNS of the EC2 instance
          REMOTE_USER: ${{ secrets.USERNAME }}          # The user to SSH with (e.g., ubuntu)
          TARGET: /var/www/html                         # Path where the files will be deployed on EC2
        with:
          args: "-rltgoDzv --rsync-path='sudo rsync' --exclude '.git/' --exclude '.github/' --delete"

      # Step 4: Ensure proper file permissions (optional)
      - name: Fix permissions on EC2
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} "sudo chown -R www-data:www-data /var/www/html && sudo chmod -R 755 /var/www/html"
