name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH and check/create the folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Step 1: Checking if the 'resume' directory exists."
            if [ ! -d /var/www/html/resume ]; then
              echo "Directory 'resume' does not exist. Creating it now."
              sudo mkdir -p /var/www/html/resume
            else
              echo "Directory 'resume' already exists."
            fi

      - name: Copy files from GitHub Actions workspace to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./"
          target: "/var/www/html/resume/"
          overwrite: true  # This will overwrite existing files with updated ones
          rm: true  # This will remove files on the server that are not in your repo
